version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: victory-cabinet
    restart: always
    env_file:
      - .env  # Link your .env file for Laravel configuration
    ports:
      - "8081:8000"
    expose:
      - "8000"
    volumes:
      - .env:/var/www/.env
      - ./storage:/var/www/storage
    networks:
      - capio
    command: php artisan serve --host=0.0.0.0 --port=8000

networks:
  capio:
    name: capio
    driver: bridge
