version: "3.9"

services:
  app:
    image: ghcr.io/andreejait/medicine-application:development
    container_name: medicine-application
    restart: always
    env_file:
      - .env  # Link your .env file for Laravel configuration
    expose:
      - "8083:8000"
    volumes:
      - .env:/var/www/.env
      - ./storage:/var/www/storage
    networks:
      - medicine-management
    command: php artisan serve --host=0.0.0.0 --port=8000

networks:
  medicine-management:
    name: medicine-management
    driver: bridge
